/* multi
line
comment
*/
DROP TABLE ORGANIZACION CASCADE;
DROP TABLE FAMILIA_CARGO CASCADE;
DROP TABLE CARGO CASCADE;
DROP TABLE FAMILIA_ROL CASCADE;
DROP TABLE ROL CASCADE;
DROP TABLE PERSONA CASCADE;
DROP TABLE PERSONA_CARGO;
DROP TABLE PERSONA_ROL;
DROP TABLE EVALUADOR;
DROP TABLE JEFE;
DROP TABLE SUPERVISOR;
DROP TABLE CORREO;
DROP TABLE USUARIO;